name: DungeonsAndRuins
main: org.monolar.DungeonsAndRuins.DungeonsAndRuinsPlugin
version: 0.1
commands:
    pos:
        description: blah
        usage: /pos
    debug:
        description: blah blah
        usage: /debug